##########################################
#### Live Stream - LIVS Config
#### Generated Using The Unity Installer
##########################################

#### Playlist
$playlist = 'STREAM02';
#### Site Name
$site = 'EI-123B';
#### Camera Name
$cam = 'ROV2';
#### Stream ID
$feed = '02';
#### Relay URL
$relay = 'ec2-107-22-0-12.compute-1.amazonaws.com';
#### Relay Endpoint
$endpoint = 'STREAM2.stream';
