##########################################
#### Live Stream - LIVS Config
#### Generated Using The Unity Installer
##########################################

#### Playlist
$playlist = 'STREAM01';
#### Site Name
$site = 'EI-123B';
#### Camera Name
$cam = 'ROV1';
#### Stream ID
$feed = '01';
#### Relay URL
$relay = 'ec2-107-22-0-12.compute-1.amazonaws.com';
#### Relay Endpoint
$endpoint = 'STREAM1.stream';
