##########################################
#### Master - LIVS Config
#### Generated Using The Unity Installer
##########################################

#### FQDN
$fqdn = 'http://ec2-107-20-67-17.compute-1.amazonaws.com/';
#### IP Address
$ip = '107.20.67.17';
#### Unity Location
$unity = 'unity';
#### Unity SQL Host
$hostname = 'localhost';
#### Unity SQL User
$username = 'unity-sql';
#### Unity SQL Pass
$password = 'pl@y1nl1vs';
#### Unity SQL Name
$database = 'unity-core';
#### Client Directory
$client = 'DEMO';
#### Project Directory
$project = 'DEMO2';
#### Temp Directory Cache Cleanup
$tmplife = '12';
#### SQL Backup Lifespan
$sqllife = '240';
#### Default FTP Location
$ftp = '/home/livs/';
#### Default LIVS Mount
$livsmount = '/mnt/unity-video/';
#### Default DOCS Mount
$docsmount = '/mnt/unity-documents/';
