require 'json'
require 'yaml'

projectDir="Base"

VAGRANTFILE_API_VERSION = "2"
confDir = $confDir ||= File.expand_path("~/.homestead")

homesteadYamlPath = confDir + "/Homestead.yaml"
homesteadJsonPath = confDir + "/Homestead.json"
afterScriptPath = confDir + "/after.sh"
aliasesPath = confDir + "/aliases"

require File.expand_path('~/Homestead/scripts/homestead.rb')

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    if File.exists? aliasesPath then
        config.vm.provision "file", source: aliasesPath, destination: "~/.bash_aliases"
    end

    if File.exists? homesteadYamlPath then
        settings = YAML::load(File.read(homesteadYamlPath))
        # set the local ln path to the shared resources
        remotePath = settings['folders'][0]['to']
    elsif File.exists? homesteadJsonPath then
        settings = JSON.parse(File.read(homesteadJsonPath))
    end

    #trigger the databases to update
    config.trigger.after :up do
      info "Loading the database from the last VM destroy..."
      run_remote  "cd " + remotePath + "/Share/Scripts; ./import-sql.sh " + projectDir
    end

    #back them up before they are gone
    config.trigger.before :destroy do
      info "Dumping the database before destroying the VM..."
      run_remote  "cd "+ remotePath + "/Share/Scripts; ./export-sql.sh " + projectDir
    end

    Homestead.configure(config, settings)

    if File.exists? afterScriptPath then
        config.vm.provision "shell", path: afterScriptPath
    end

    if defined? VagrantPlugins::HostsUpdater
        config.hostsupdater.aliases = settings['sites'].map { |site| site['map'] }
    end

end